name: SurvivalGamesV3
main: SurvivalGamesV3\SurvivalGamesV3
version: 3.0.3
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer


commands:
    sg:
        usage: /s
        description: A full list of SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
